openapi: 3.0.0
info:
  title: GrandChef API
  version: 1.0.0
paths:
  /api/categorias:
    get:
      summary: Listar todas as categorias
      tags:
        - Categorias
      responses:
        '200':
          description: Lista de categorias
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    example: 2
                  por_pagina:
                    type: integer
                    example: 10
                  pagina:
                    type: integer
                    example: 1
                  ultima_pagina:
                    type: integer
                    example: 1
                  dados:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        nome:
                          type: string
                          example: "Bebidas"
                        produtos:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                                example: 1
                              nome:
                                type: string
                                example: "Produto Exemplo"
    post:
      summary: Criar uma nova categoria
      tags:
        - Categorias
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  example: "Bebidas"
      responses:
        '201':
          description: Categoria criada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  nome:
                    type: string
                    example: "Bebidas"
        '400':
          description: Requisição inválida

  /api/categorias/{id}:
    get:
      summary: Exibir uma categoria específica
      tags:
        - Categorias
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: Categoria encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  nome:
                    type: string
                    example: "Bebidas"
                  produtos:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        nome:
                          type: string
                          example: "Produto Exemplo"
        '404':
          description: Categoria não encontrada
    put:
      summary: Atualizar uma categoria existente
      tags:
        - Categorias
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            default: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  example: "Bebidas"
      responses:
        '200':
          description: Categoria atualizada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  nome:
                    type: string
                    example: "Bebidas"
        '404':
          description: Categoria não encontrada
    delete:
      summary: Excluir uma categoria
      tags:
        - Categorias
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: Categoria excluída com sucesso
        '404':
          description: Categoria não encontrada

  /api/produtos:
    get:
      summary: Listar todos os produtos
      tags:
        - Produtos
      responses:
        '200':
          description: Lista de produtos
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    example: 2
                  por_pagina:
                    type: integer
                    example: 10
                  pagina:
                    type: integer
                    example: 1
                  ultima_pagina:
                    type: integer
                    example: 1
                  dados:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        nome:
                          type: string
                          example: "Coca-Cola"
                        preco:
                          type: number
                          format: float
                          example: 5.99
                        categoria:
                          type: object
                          example: {}
    post:
      summary: Criar um novo produto
      tags:
        - Produtos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  example: "Coca-Cola"
                preco:
                  type: number
                  format: float
                  example: 5.99
      responses:
        '201':
          description: Produto criado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  nome:
                    type: string
                    example: "Coca-Cola"
                  preco:
                    type: number
                    format: float
                    example: 5.99
                  categoria_id:
                    type: integer
                    example: 1
        '400':
          description: Requisição inválida
  /api/pedidos:
    get:
      summary: Listar todos os pedidos
      tags:
        - Pedidos
      responses:
        '200':
          description: Lista de pedidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    example: 2
                  por_pagina:
                    type: integer
                    example: 10
                  pagina:
                    type: integer
                    example: 1
                  ultima_pagina:
                    type: integer
                    example: 1
                  dados:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        produtos:
                          type: array
                          items:
                            type: object
                            properties:
                              produto_id:
                                type: integer
                                example: 1
                              preco:
                                type: number
                                format: float
                                example: 5.99
                              quantidade:
                                type: integer
                                example: 2
                        estado:
                          type: string
                          enum:
                            - aberto
                            - aprovado
                            - concluido
                            - cancelado
                          example: "aberto"

    post:
      summary: Criar um novo pedido
      tags:
        - Pedidos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                produtos:
                  type: array
                  items:
                    type: object
                    properties:
                      produto_id:
                        type: integer
                        example: 1
                      preco:
                        type: number
                        format: float
                        example: 5.99
                      quantidade:
                        type: integer
                        example: 2
      responses:
        '201':
          description: Pedido criado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  produtos:
                    type: array
                    items:
                      type: object
                      properties:
                        produto_id:
                          type: integer
                          example: 1
                        preco:
                          type: number
                          format: float
                          example: 5.99
                        quantidade:
                          type: integer
                          example: 2
                  estado:
                    type: string
                    enum:
                      - aberto
                      - aprovado
                      - concluido
                      - cancelado
                    example: "aberto"
        '400':
          description: Requisição inválida

  /api/pedidos/{id}:
    get:
      summary: Exibir um pedido específico
      tags:
        - Pedidos
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: Pedido encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  produtos:
                    type: array
                    items:
                      type: object
                      properties:
                        produto_id:
                          type: integer
                          example: 1
                        preco:
                          type: number
                          format: float
                          example: 5.99
                        quantidade:
                          type: integer
                          example: 2
                  estado:
                    type: string
                    enum:
                      - aberto
                      - aprovado
                      - concluido
                      - cancelado
                    example: "aberto"
        '404':
          description: Pedido não encontrado
    put:
      summary: Atualizar um pedido existente
      tags:
        - Pedidos
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            default: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                estado:
                  type: string
                  enum:
                    - aberto
                    - aprovado
                    - concluido
                    - cancelado
                  example: "concluido"
      responses:
        '200':
          description: Pedido atualizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  estado:
                    type: string
                    enum:
                      - aberto
                      - aprovado
                      - concluido
                      - cancelado
                    example: "concluido"
        '404':
          description: Pedido não encontrado
